version: '3.8'

services:
  sqlserver:
    build:
      context: ./sqlserver
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Grupo1@BDD!
    networks:
      - etl_network
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Grupo1@BDD!' -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=etl_user
      - POSTGRES_PASSWORD=Grupo1_PG!
      - POSTGRES_DB=etl_destino
    networks:
      - etl_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U etl_user -d etl_destino" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  etl_network:
    driver: bridge
